enable_topic_start_from_top:
  type: bool
  default: true
  description: "Enable starting topics from top instead of last read position"

exclude_user_groups:
  type: list
  default: ""
  description: "Exclude specific user groups (enter group names separated by |)"

throttle_interval:
  type: integer
  default: 300
  description: "Throttle interval in milliseconds to prevent API overload" 